# A Docker Compose For running the Cloud Run image locally
version: '3'
services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: mysecretpassword
  micronaut-starter:
    image: micronaut-starter
    links:
      - postgres    
    ports:
      - 8080:8080
    environment:
      DATASOURCES_DEFAULT_URL: postgres
      DATASOURCES_DEFAULT_USERNAME: postgres
      DATASOURCES_DEFAULT_PASSWORD: mysecretpassword
 
